
import React from 'react';
import BandsintownWidgetStyles from './BandsintownWidgetStyles';

const BandsintownWidget = () => {
  return (
    <div className="bit-widget-container hover:scale-[1.01] transition-transform duration-300">
      <BandsintownWidgetStyles />
      <a 
        className="bit-widget-initializer"
        data-artist-name="id_15568391"
        data-events-to-display=""
        data-background-color="rgba(19, 18, 26, 0.8)"
        data-separator-color="rgba(155, 135, 245, 0.3)"
        data-text-color="rgba(255, 193, 203, 1)"
        data-font="Jacquard 12"
        data-auto-style="false"
        data-button-label-capitalization="lowercase"
        data-header-capitalization="lowercase"
        data-location-capitalization="lowercase"
        data-venue-capitalization="lowercase"
        data-display-local-dates="true"
        data-local-dates-position="tab"
        data-display-past-dates="true"
        data-display-details="false"
        data-display-lineup="false"
        data-display-start-time="false"
        data-social-share-icon="false"
        data-display-limit="all"
        data-date-format="MMM. D, YYYY"
        data-date-orientation="horizontal"
        data-date-border-color="#9b87f5"
        data-date-border-width="1px"
        data-date-capitalization="lowercase"
        data-date-border-radius="0px"
        data-event-ticket-cta-size="medium"
        data-event-custom-ticket-text=""
        data-event-ticket-text="tickets"
        data-event-ticket-icon="false"
        data-event-ticket-cta-text-color="rgba(19, 18, 26, 1)"
        data-event-ticket-cta-bg-color="rgba(155, 135, 245, 1)"
        data-event-ticket-cta-border-color="rgba(155, 135, 245, 1)"
        data-event-ticket-cta-border-width="0px"
        data-event-ticket-cta-border-radius="0px"
        data-sold-out-button-text-color="rgba(255, 193, 203, 1)"
        data-sold-out-button-background-color="rgba(19, 18, 26, 0.5)"
        data-sold-out-button-border-color="rgba(255, 193, 203, 0.5)"
        data-sold-out-button-clickable="true"
        data-event-rsvp-position="left"
        data-event-rsvp-cta-size="medium"
        data-event-rsvp-only-show-icon="false"
        data-event-rsvp-text="rsvp"
        data-event-rsvp-icon="false"
        data-event-rsvp-cta-text-color="rgba(155, 135, 245, 1)"
        data-event-rsvp-cta-bg-color="rgba(19, 18, 26, 0.8)"
        data-event-rsvp-cta-border-color="rgba(155, 135, 245, 0.5)"
        data-event-rsvp-cta-border-width="1px"
        data-event-rsvp-cta-border-radius="0px"
        data-follow-section-position="top"
        data-follow-section-alignment="center"
        data-follow-section-header-text="get updates on new shows, new music, and more"
        data-follow-section-cta-size="medium"
        data-follow-section-cta-text="follow"
        data-follow-section-cta-icon="false"
        data-follow-section-cta-text-color="rgba(19, 18, 26, 1)"
        data-follow-section-cta-bg-color="rgba(155, 135, 245, 1)"
        data-follow-section-cta-border-color="rgba(155, 135, 245, 1)"
        data-follow-section-cta-border-width="0px"
        data-follow-section-cta-border-radius="0px"
        data-play-my-city-position="bottom"
        data-play-my-city-alignment="center"
        data-play-my-city-header-text="don't see a show near you?"
        data-play-my-city-cta-size="medium"
        data-play-my-city-cta-text="request a show"
        data-play-my-city-cta-icon="false"
        data-play-my-city-cta-text-color="rgba(19, 18, 26, 1)"
        data-play-my-city-cta-bg-color="rgba(155, 135, 245, 1)"
        data-play-my-city-cta-border-color="rgba(155, 135, 245, 1)"
        data-play-my-city-cta-border-width="0px"
        data-play-my-city-cta-border-radius="0px"
        data-language="en"
        data-layout-breakpoint="900"
        data-app-id="js_e7788911-f441-44f5-8ade-039a101a9f21"
        data-bit-logo-position="bottomRight"
        data-bit-logo-color="rgba(155, 135, 245, 0.7)"
      ></a>
    </div>
  );
};

export default BandsintownWidget;
